export const ADD_POST = 'ADD_POST';

export const FETCH_LIST_POST_FAIL = 'FETCH_LIST_POST_FAIL';
export const FETCH_LIST_POST_IS_PENDING = 'FETCH_LIST_POST_IS_PENDING';
export const FETCH_LIST_POST_SUCCESS = 'FETCH_LIST_POST_SUCCESS';
